"""Search for static references to a 64-bit address in the module.
   Looks at: lea reg, [rip+disp] resolving to target; movabs reg, imm64; raw bytes in .rdata/.data."""
import struct, sys, capstone
from capstone.x86 import X86_OP_IMM, X86_OP_MEM, X86_OP_REG

from _paths import DLL_PATH as DLL, require
DLL = require("CHERAX_MODULE", DLL)

target = int(sys.argv[1], 16) if len(sys.argv) > 1 else 0x180e99fed

def load_sections():
    with open(DLL, "rb") as f:
        data = f.read()
    e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    opt_sz = struct.unpack_from("<H", data, e_lfanew + 0x14)[0]
    nsec = struct.unpack_from("<H", data, e_lfanew + 0x06)[0]
    image_base = struct.unpack_from("<Q", data, e_lfanew + 4 + 20 + 24)[0]
    sec_off = e_lfanew + 4 + 20 + opt_sz
    secs = []
    for i in range(nsec):
        off = sec_off + i*40
        name = data[off:off+8].rstrip(b"\0").decode("ascii", "replace")
        vsize, vaddr, rawsz, rawoff = struct.unpack_from("<IIII", data, off+8)
        sz = min(vsize, rawsz)
        secs.append((name, image_base+vaddr, data[rawoff:rawoff+sz]))
    return secs

secs = load_sections()
print(f"Searching for refs to {target:#x}")

# 1) Raw 64-bit bytes in any data section
target_le = target.to_bytes(8, 'little')
target32 = (target & 0xFFFFFFFF).to_bytes(4, 'little')
for name, base, buf in secs:
    if name.startswith('.text') or name.startswith('.cpax'): continue
    i = 0
    print(f"\n--- raw bytes in {name} (qword) ---")
    n = 0
    while True:
        i = buf.find(target_le, i)
        if i == -1: break
        print(f"  {base+i:#011x}  (qword)")
        n += 1
        i += 1
    print(f"  total qword: {n}")

# 2) Disassemble .text and .cpax, look for LEA RIP-relative or movabs that produce target
md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
md.detail = True
md.skipdata = True

for name, base, buf in secs:
    if not (name == '.text' or name == '.cpax'): continue
    print(f"\n--- disasm refs in {name} ---")
    n = 0
    for ins in md.disasm(buf, base):
        try: ops = ins.operands
        except: continue
        if ins.mnemonic == 'lea':
            if len(ops) < 2 or ops[1].type != X86_OP_MEM: continue
            mem = ops[1].mem
            if mem.base == 0 or mem.index != 0: continue
            try:
                bname = md.reg_name(mem.base)
            except: continue
            if bname != 'rip': continue
            ea = ins.address + ins.size + mem.disp
            ea &= 0xFFFFFFFFFFFFFFFF
            if ea == target:
                print(f"  {ins.address:#011x}  {ins.mnemonic:<8}{ins.op_str}")
                n += 1
        elif ins.mnemonic == 'movabs':
            if len(ops) < 2 or ops[1].type != X86_OP_IMM: continue
            if ops[1].imm == target:
                print(f"  {ins.address:#011x}  {ins.mnemonic:<8}{ins.op_str}")
                n += 1
        elif ins.mnemonic == 'mov':
            # mov reg64, imm64 isn't generated by capstone as 'mov' normally; movabs covers it
            if len(ops) < 2: continue
            if ops[1].type == X86_OP_IMM and ops[1].imm == target:
                print(f"  {ins.address:#011x}  {ins.mnemonic:<8}{ins.op_str}")
                n += 1
        elif ins.mnemonic == 'push':
            if len(ops) < 1: continue
            if ops[0].type == X86_OP_IMM and ops[0].imm == target:
                print(f"  {ins.address:#011x}  {ins.mnemonic:<8}{ins.op_str}")
                n += 1
    print(f"  total: {n}")
